export const CHANGE_VIEW = "CHANGE_VIEW";

export const SET_GET_ALL_PRINCIPALS_STATUS = "SET_GET_ALL_PRINCIPALS_STATUS";
export const SET_GET_ALL_PRINCIPALS_VALUE = "SET_GET_ALL_PRINCIPALS_VALUE";
export const SET_PRINCIPAL_VALUE = "SET_PRINCIPAL_VALUE";
export const SET_ADD_PRODUCT_STATUS = "SET_ADD_PRODUCT_STATUS";
export const SET_EDIT_PRINCIPAL_STATUS = "SET_EDIT_PRINCIPAL_STATUS";
export const SET_ADD_PRINCIPAL_STATUS = "SET_ADD_PRINCIPAL_STATUS";
export const SET_PRODUCT_VALUE = "SET_PRODUCT_VALUE";
export const SET_EDIT_PRODUCT_STATUS = "SET_EDIT_PRODUCT_STATUS";
export const SET_PRODUCT_STATE_STATUS = "SET_PRODUCT_STATE_STATUS";
export const SET_PRINCIPAL_STATE_STATUS = "SET_PRINCIPAL_STATE_STATUS";

export const SET_GET_GROUPS_STATUS = "SET_GET_GROUPS_STATUS";
export const SET_GET_GROUPS_VALUE = "SET_GET_GROUPS_VALUE";
export const SET_ADD_GROUP_STATUS = "SET_ADD_GROUP_STATUS";
export const SET_GROUP_VALUE = "SET_GROUP_VALUE";
export const SET_EDIT_GROUP_STATUS = "SET_EDIT_GROUP_STATUS";
export const SET_GROUP_STATE_STATUS = "SET_GROUP_STATE_STATUS";

export const SET_GET_ROLES_STATUS = "SET_GET_ROLES_STATUS";
export const SET_GET_ROLES_VALUE = "SET_GET_ROLES_VALUE";
export const SET_ADD_ROLE_STATUS = "SET_ADD_ROLE_STATUS";
export const SET_EDIT_ROLE_STATUS = "SET_EDIT_ROLE_STATUS";
export const SET_ROLE_VALUE = "SET_ROLE_VALUE";

export const SET_GET_USERS_STATUS = "SET_GET_USERS_STATUS";
export const SET_GET_USERS_VALUE = "SET_GET_USERS_VALUE";
export const SET_ADD_USER_VALUE = "SET_ADD_USER_VALUE";
export const SET_GET_USER_STATUS = "SET_GET_USER_STATUS";
export const SET_USER_VALUE = "SET_USER_VALUE";
export const SET_EDIT_USER_STATUS = "SET_EDIT_USER_STATUS";

export const SET_UPDATE_USER_PRODUCT_STATUS = "SET_UPDATE_USER_PRODUCT_STATUS";